# Generated by Django 4.2.1 on 2023-09-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('link', models.SlugField(max_length=200)),
                ('duration', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=10)),
                ('status', models.BooleanField()),
                ('viewTime', models.IntegerField(max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.product'),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.product')),
            ],
        ),
    ]
