# Generated by Django 4.2.1 on 2023-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='userID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='userID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='view',
            name='viewTime',
            field=models.IntegerField(),
        ),
    ]
