# Generated by Django 4.2.1 on 2023-09-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_alter_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutor.view'),
        ),
    ]
